#' @title Filter RNAi hits based on expression thresholds
#'
#' @description
#' This function filters the raw RNAi hits data frame to retain only contigs
#' that are relevant in term of expression. The filtering is performed in two steps:
#' 1. **Group minimum expression criterion**: keeps a gene if it has CPM greater than
#'    or equal to \code{cpm_cut_group} in all samples of at least one group.
#' 2. **Global minimum expression criterion**: keeps a gene if it has CPM greater than
#'    or equal to \code{cpm_cut_global} in at least the minimal number of replicates across all samples.
#'
#' @param raw_rnai_hits A data frame containing RNAi hits, typically generated by \code{\link{search.rnai}}.
#' @param expression_df A data frame of raw counts with contigs as rows and sample names as columns.
#' @param groups_df A data frame describing sample groupings, with columns \code{SAMPLE} and \code{REP}.
#' @param cpm_cut_group Numeric. Threshold CPM value for the group minimum expression filter. Default is 1.
#' @param cpm_cut_global Numeric. Threshold CPM value for the global minimum expression filter. Default is 10.
#'
#' @return A filtered RNAi hits data frame containing only the contigs that pass both filters.
#'
#' @details This function uses the \code{edgeR::cpm()} function to calculate Counts Per Million (CPM) from raw counts.
#' It prints a report summarizing the number of genes removed at each filtering step.
#'
#' @examples
#' \dontrun{
#' # Filtering RNAi hits using default thresholds:
#' raw_rnai_hits <- search.rnai(annotation_df = annotation, column = "Top_BLASTX_hit")
#' expression_df <- read.table("raw_counts.txt")
#' groups_df <- read.table("samples.txt")
#'
#'
#' filtered_rnai_hits <- expr.filter(raw_rnai_hits, expression_df, groups_df)
#' }
#'
#' @importFrom edgeR cpm
#' @export

expr.filter <- function(raw_rnai_hits, expression_df, groups_df, cpm_cut_group = 1, cpm_cut_global = 10){
  # Input validation
  validate.inputs(rnai_hits = raw_rnai_hits,
                  expression_df = expression_df,
                  groups_df = groups_df,
                  cpm_cut = c(cpm_cut_group, cpm_cut_global)
  )

  # Merge keeping only protein annotation's present in the expression dataframe, and preserve they order
  gene_present <- raw_rnai_hits$GeneID[raw_rnai_hits$GeneID %in% rownames(expression_df)]
  expr_sub <- expression_df[gene_present, , drop = FALSE]

  # Calculate CPM with edgeR
  cpm <- edgeR::cpm(expr_sub)

  #Pick up the groups and number of replicates
  groups <- groups_df$REP
  samples <- groups_df$SAMPLE
  min_reps <- max(table(groups_df$SAMPLE))

  # Group samples and applies first filter (per groups)
  keep_genes <- apply(cpm, 1, function(gene_row) {
    tapply(seq_along(gene_row), samples, function(idxs) all(gene_row[idxs] >= cpm_cut_group)) |> any()
  })
  expr_filtered <- expr_sub[keep_genes, , drop = FALSE]

  # Apply second filter (global)
  keep_genes2 <- rowSums(edgeR::cpm(expr_filtered) >= cpm_cut_global) >= min_reps
  expr_filtered <- expr_filtered[keep_genes2, , drop = FALSE]

  # Update found genes list with the filtered ones
  filtered_rnai_hits <- raw_rnai_hits[raw_rnai_hits$GeneID %in% rownames(expr_filtered), , drop = FALSE]

  # Report
  total_genes <- nrow(expr_sub)
  after_group <- sum(keep_genes)
  after_global <- sum(keep_genes2)

  cat("~~ Report of genes filtering ~~\n",
      "Total pre filter:", total_genes, "genes.\n",
      "Removed by group minimum CPM criterion:", total_genes - after_group, "genes.\n",
      "Removed by global minimum CPM criterion:", after_group - after_global, "genes.\n",
      "Total post filter:", after_global, "genes.\n")

  # Return filtered rnai_hits dataframe
  return(filtered_rnai_hits)
}
