#' @title Plot a heatmap of RNAi core genes expression across samples
#'
#' @description
#' This function plots a heatmap representing the expression of RNAi core genes
#' across samples. The data can be normalized using log2 CPM, Z-score, or left unnormalized.
#'
#' @param rnai_hits A data frame containing RNAi hits, typically generated by
#'   \code{\link{search.rnai}} or \code{\link{expr.filter}}. Must contain the columns
#'   "GeneID" and "ProteinAnnotation".
#' @param expression_df A data frame of raw counts with contigs as rows and sample names as columns.
#' @param normalize Character string specifying the normalization method to apply to the counts.
#'   Options are \code{"logCPM"} (default), \code{"zscore"}, or \code{"none"}.
#' @param save Logical; if \code{TRUE}, the heatmap will be saved as a PNG file.
#'   Default is \code{FALSE}.
#' @param path Character string specifying the file path to save the PNG file.
#'   If \code{NULL}, the heatmap will be saved in the current working directory
#'   with the default name "heatmap_plot.png".
#'
#' @return A \code{ComplexHeatmap} object representing the expression of RNAi core genes.
#'
#' @examples
#' \dontrun{
#' raw_rnai_hits <- search.rnai(annotation_df = annotation, column = "Top_BLASTX_hit")
#' expression_df <- read.table("raw_counts.txt")
#'
#' # Plot heatmap with default logCPM normalization
#' heatmap_plot <- heatmap.plot(raw_rnai_hits, expression_df)
#'
#' # Save heatmap as PNG
#' heatmap_plot <- heatmap.plot(raw_rnai_hits, expression_df, save = TRUE, path = "my_heatmap.png")
#' }
#'
#' @importFrom ComplexHeatmap Heatmap draw
#' @importFrom edgeR DGEList cpm
#' @importFrom grDevices png dev.off
#' @importFrom grid gpar
#'
#' @export

heatmap.plot <- function(rnai_hits, expression_df, normalize = c("logCPM", "zscore", "none"), save = FALSE, path = NULL){
  # Merge keeping only protein annotation's present in the expression dataframe, and preserve they order
  gene_present <- rnai_hits$GeneID[rnai_hits$GeneID %in% rownames(expression_df)]
  heatmap_data <- expression_df[gene_present, , drop = FALSE]

  # Change rownames to ProteinAnnotation
  rownames(heatmap_data) <- rnai_hits$ProteinAnnotation[rnai_hits$GeneID %in% gene_present]

  # Input validation
  validate.inputs(rnai_hits = rnai_hits,
                  expression_df = expression_df,
                  normalize = normalize,
                  save = save,
                  path = path
  )
  if (nrow(heatmap_data) ==0){
    stop("Cannot plot a heatmap because none of the RNAi hits are found in the expression matrix.")
  }

  # Normalizing data before plot
  normalize <- match.arg(normalize)

  mat <- as.matrix(heatmap_data)

  if (normalize == "logCPM") {
    dge <- edgeR::DGEList(counts = mat)
    mat <- edgeR::cpm(dge, log = TRUE, prior.count = 1)
  }

  if (normalize == "zscore") {
    dge <- edgeR::DGEList(counts = mat)
    mat <- edgeR::cpm(dge, log = TRUE, prior.count = 1)
    mat <- t(scale(t(mat)))
  }

  if (normalize == "none") {
    mat <- as.matrix(mat)
  }

  # Plot
  legend_name <- switch(
    normalize,
    "logCPM" = "log2 CPM",
    "zscore" = "Z-score",
    "none"   = "Expression"
  )
  plot <- ComplexHeatmap::Heatmap(mat, name = legend_name, row_names_side = "left", cluster_columns = FALSE, row_names_gp = gpar(fontsize = 10))

  # Draw in viewer
  ComplexHeatmap::draw(plot)

  # Export plot
  if (isTRUE(save)) {
    if (is.null(path)) {
      path <- file.path(getwd(), "heatmap_plot.png")
    }
    png(path, width = 2000, height = 1800, res = 300)
    ComplexHeatmap::draw(plot)
    dev.off()
    message("Heatmap plot saved in: ", path)
  }

  return(plot)
}
