#' Report summary of RNAi core machinery genes
#'
#' Internal function that counts the number of RNAi core genes identified in each category
#' and prints a summary of total and per-category hits.
#'
#' @param rnai_hits A data frame containing RNAi hits, typically generated by
#'   \code{\link{search.rnai}} or \code{\link{expr.filter}}. Must contain the
#'   column \code{"Category"}.
#'
#' @importFrom stats setNames
#'
#' @keywords internal

report.machinery <- function(rnai_hits) {
  # Input validation
  validate.inputs(rnai_hits = rnai_hits)

  # Define categories to count
  expected_categories <- c(
    "Argonautes",
    "Auxiliary RISC-associated",
    "Dicer family",
    "dsRNA binding",
    "dsRNA transport/uptake"
  )

  # Do counts per categories keeping the expected levels
  counts_df <- as.data.frame(table(factor(rnai_hits$Category, levels = expected_categories)))
  colnames(counts_df) <- c("Category","Count")

  # Named vector to lookup
  counts_named <- setNames(as.integer(counts_df$Count), counts_df$Category)

  # Print
  cat("~~ Summary of identified RNAi core machinery genes ~~\nTotal:", nrow(rnai_hits), "hits.\n")

  for (cat_name in expected_categories) {
    count <- counts_named[cat_name]
    if (is.na(count)) count <- 0
    cat(cat_name, ":", count, "hits.\n")
  }
}
